version: '3.7'

services:
  bot:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 9090 --debug 
    #command: gunicorn --bind 0.0.0.0:9090 app.main:app -c gunicorn.conf.py --reload
    #command: gunicorn app.main:app -c gunicorn.conf.py
    volumes:
      - .:/app
    ports:
      - 9090:9090
